### PR TITLE
Use universal references in append() method

### PR DESCRIPTION
**Pull request by dota17**
This litte patch fixes issue #1046.

### CODE REVIEW

**Comment by BillyDonahue** [comment]
This is not a "universal reference" (which are now called "forwarding references").
It's an rvalue reference.

Anyway, for an "append" member function I'm looking at copying the API of standard container members like vector::push_back, which will always have a const T& and a T&& overload.

The Microsoft.co.il blog referred to in #1046 is having an internal problem right now so I can't read it, but I haven't heard of the {const T&, T&&} overload set as being a problem for append methods before.

**Comment by BillyDonahue** [comment]
@dota17 can we close this PR now?

**Comment by dota17** [comment]
> @dota17 can we close this PR now?

@BillyDonahue 
if we close this PR, then how can we treat this issue #1046?
and how about the `insert` method?

**Comment by BillyDonahue** [comment]
@dota17 you are right. We should get a consensus on #1046 before closing this.

**Comment by dota17** [comment]
Closing.  See the dicussion in #1046.

**Comment by cdunn2001** [comment]
I hope Billy and Jordan don't feel as if they've wasted their own time on this. Personally, this was very informative for me, including the experiments. So I'm glad you tried this, Chen.

**Comment by dota17** [comment]
> I hope Billy and Jordan don't feel as if they've wasted their own time on this. Personally, this was very informative for me, including the experiments. So I'm glad you tried this, Chen.

Yes, I agree, the experiments for this issue are very important. Thanks to Billy and Jordan's experiments. we have a clear and and reliable conclusions for that now.

**Pull request closed without merging**
