### PR TITLE
Hotfix for compile issue #659

### PR DESCRIPTION
**Pull request by SloCompTech**
Fix for compile issue when compile there were error in `config.h` and `value.h` in pre-processing code, details in issue #659.

### CODE REVIEW

**Comment by SloCompTech** [comment]
I also fixed instructions for install where parameters were switched

**Comment by cdunn2001** [comment]
* The README fix is good.
* The C++11 setting is fine. I'm not sure it's needed, but we don't want to support non-C++11 anyway.
* I'm not sure about the `JSONCPP_USING_SECURE_MEMORY` change. Someone might be relying on `0` as false. Note that `version.h` sets that to `0` if it was not defined, which is the proper logic.

Maybe there is a different problem with the Meson build, where version.h is somehow dropped?

**Comment by SloCompTech** [comment]
Fixed readme, temporary fixed compile bug with adding `jsoncpp_cdata.set('JSONCPP_USE_SECURE_MEMORY',0)` in meson build config, that means that use of secure memory is disabled, but if you compile any program with `-ljsoncpp` it works, but if you enable USE_SECURE_MEMORY, then you get error on `asString()` method 
```
ConfigModule.cpp:252:54: error: conversion from ‘std::__cxx11::basic_string<char, std::char_traits<char>, Json::SecureAllocator<char> >’ to non-scalar type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ requested
           std::string text = entry[OPT_TYPE].asString();
```

**Comment by cdunn2001** [comment]
For our future reference:

* http://mesonbuild.com/Configuration.html
* http://mesonbuild.com/Reference-manual.html

**Pull request merged**
