### PR TITLE
Provide JSONCPP_DEPRECATED definitions for clang and gcc

### PR DESCRIPTION
**Pull request by Dani-Hub**
Extended definitions of JSONCPP_DEPRECATED

### CODE REVIEW

**Comment by cdunn2001** [comment]
Looks like there was a problem for gcc:
```
Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_reader.cpp.o
In file included from /home/travis/build/open-source-parsers/jsoncpp/include/json/assertions.h:13:0,
                 from /home/travis/build/open-source-parsers/jsoncpp/src/lib_json/json_reader.cpp:7:
/home/travis/build/open-source-parsers/jsoncpp/include/json/config.h:73:45: error: missing binary operator before token "("
```
After you fix that, I'll try to test with VisualStudio.

**Comment by Dani-Hub** [comment]
Could you please provide me the gcc version (major and minor numbers or full version) that you have used for your testing?

**Comment by Dani-Hub** [comment]
The revised commit has been tested successfully against gcc 4.3.6, 4.4.7, 4.5.4, 4.6.4, 4.7.3, 4.8.1, 4.9.0, 4.9.1, 4.9.2, and HEAD 5.0.0 as well as against clang 3.0, 3.1, 3.2, 3.3, 3.4, 3.5.0, 3.6.0, and HEAD 3.7.0 and finally against Visual Studio 2012

**Comment by cdunn2001** [comment]
Nice! Thanks.

**Pull request closed without merging**
