### PR TITLE
C++11 enhancement - Use range-based for

### PR DESCRIPTION
**Pull request by ya1gaurav**
C++11 provides enhancement for range-based for loops specially for containers. It improves readability.
Reference : http://en.cppreference.com/w/cpp/language/range-for

### CODE REVIEW

**Comment by cdunn2001** [comment]
Is there any performance improvement? Faster compilation?

**Comment by ya1gaurav** [comment]
1. Easy to code.
2. Improved readability.
3. No need to dereference the iterator to get the value.

**Comment by cdunn2001** [comment]
None of those advantages apply to users.

In general, I don't like altering a code-base for aesthetic reasons. If we accept these changes, I expect a never-ending supply of similar submissions. And in this case, it would increase the disparities between the new and old branches, making the project harder to maintain. The old branch is actually the more popular.

**Comment by ya1gaurav** [comment]
Its ok, these are just c++-11 style coding.

**Comment by cdunn2001** [comment]
Thanks for understanding. I don't mean to offend you. We always appreciate contributions.

**Pull request closed without merging**
