### PR TITLE
Json::Value constructor: Accept any arithmetic type.

### PR DESCRIPTION
**Pull request by BillyDonahue**
Allow construction of Json::Value from size_t, short, etc.
Fixes issue #64

### CODE REVIEW

**Comment by cdunn2001** [comment]
Since the main branch is strictly C++11 now, will this solution work? What about MSVC?

**Comment by BillyDonahue** [comment]
In C++11 a much more elegant version of this code would be possible.
So I'd rewrite it for the main branch using the C++11 common subset supported by MSVC.
How far back into MSVC do you need to support? Their C++11 compliance is a moving target.

**Comment by cdunn2001** [comment]
2013 at the earliest. I'm even fine with 2015. Folks with a problem can always use an older release.

At some point, you might have to break some API-compatibility. In that case, put it on a 2.y.z branch. I expect most C++11 changes will break binary compatibility anyway.

Hmmm. I really need to get the hidden implementation done quickly, so it will not conflict with other new work. But just do what you think best.

**Comment by hjmjohnson** [comment]
@BillyDonahue I'm closing this 4 year old PR.  I think that the move to C++11 makes this PR not consistent with the current code base.

If there are still changes that are needed, please feel free to re-open the PR (preferably rebased on top of the current master branch).

**Pull request closed without merging**
