### PR TITLE
Use standard CMake variables - static/shared lib.

### PR DESCRIPTION
**Pull request by ya1gaurav**
Replace JSONCPP_LIB_BUILD_SHARED => BUILD_SHARED_LIBS
Replace JSONCPP_LIB_BUILD_STATIC => BUILD_STATIC_LIBS
Removed workaround  https://github.com/open-source-parsers/jsoncpp/issues/51
Removed OPTION for shared/static in this file.

### CODE REVIEW

**Comment by ya1gaurav** [comment]
Why it failed, is this pull request built standalone?
It need to build all pulls under "Use standard CMake variables - static/shared lib." simultaneously.
They are dependent.

**Comment by ya1gaurav** [comment]
Or how can combine in one pull request ?

**Comment by cdunn2001** [comment]
Create your pull-request for a single branch. Then put each new commit on the same branch, and push to github. The pull-request will automatically be updated, and it will automatically re-run the tests.

I've done that in #263. We can discuss it there, or you can re-create if you want. I will close your previous PRs, since there are so many.

**Comment by ya1gaurav** [comment]
Thanks, I will take care next time.

**Pull request closed without merging**
