### PR TITLE
__cplusplus value should not be used to decide for std::unique_ptr #350:

### PR DESCRIPTION
**Pull request by Dani-Hub**
In addition to the C++ language version define __cplusplus also check _CPPLIB_VER for better Dinkumware support.

### CODE REVIEW

**Comment by cdunn2001** [comment]
I lost track of the conversation on this. Was there any objection?

If not, could you rebase this to the current tip of `master`?

**Comment by Dani-Hub** [comment]
I'm not aware of any objections. Should I select "Close and comment" instead of "Comment" to signal that I'm happy?

**Comment by cdunn2001** [comment]
That looks like a merge-commit. Could you rebase? If you don't know how, that's fine. I can do it.

**Comment by BillyDonahue** [comment]
I just learned the difference between rebase and merge commits:
http://git-scm.com/book/ch3-6.html Might be helpful.

**Comment by Dani-Hub** [comment]
OK, I'll try a rebase this evening.

**Comment by Dani-Hub** [comment]
I was busy the last two days, but please let my try to that on my own during the weekend.

**Comment by Dani-Hub** [comment]
Replaced by the rebased pull request #367

**Comment by cdunn2001** [comment]
Note that you can rebase a pull-request without opening a new one:
```
git rebase ...
git push -f origin issue-350-unique_ptr
```
GitHub would magically update *this* PR. It's a nice feature.

**Pull request closed without merging**
