### PR TITLE
Re-add JSONCPP_NORETURN replacing [[noreturn]]

### PR DESCRIPTION
**Pull request by es1x**
Restores Visual Studio 2013 compatibility.

### CODE REVIEW

**Comment by dota17** [comment]
Can you post more info?
I am wondering the errors or other messages about the Visual Studio 2013 compatibility.

**Comment by es1x** [comment]
The `[[noreturn]]` clause causes the following compilation errors, apparently as a result of incomplete C++11 support:
Capture

**Comment by dota17** [comment]
When I used VS 2013 to build, I got the same result.
The problem is that the newest code which include `[[noreturn]]` requires more C++11 features, but VS 2013 doesn't support C++11 attributes feature.
Related Solution Link: [C3409](https://stackoverflow.com/questions/32815196/c3409-empty-attribute-block-is-not-allowed-by-noreturn)

According to the git history, in the commit [408b466b](https://github.com/open-source-parsers/jsoncpp/commit/408b466b57f4cf0744c2ab3de1c700dc83fc24fc#diff-180360612c6b8c4ed830919bbb4dd459),  the test for Visual Studio 12 2013 had been removed.
Maybe there are some other places/commits that require more C++11 features.

And I found some places that we may need to change if we do not re-add JSONCPP_NORETURN.
etc, in include/json/config.h
```
#if defined(_MSC_VER) && _MSC_VER < 1800
#error                                                                         \
    "ERROR:  Visual Studio 12 (2013) with _MSC_VER=1800 is the oldest supported compiler with sufficient C++11 capabilities"
#endif
```
Maybe Visual Studio 12 (2013) with _MSC_VER=1800 is not the oldest anymore.

**Comment by baylesj** [comment]
I think the value add of dropping a macro is not worth dropping support for your IDE. I'll look at adding more CI coverage.

**Pull request merged**
