### PR TITLE
Issue 1066

### PR DESCRIPTION
**Pull request by BillyDonahue**
Julian I took out the macros and tried to compress the unit tests a bit.
It's just a suggestion. You can take it or leave it, really.

### CODE REVIEW

**Comment by cdunn2001** [comment]
TIL about "Draft" pull-requests. Anyway, this is interesting. (re: #1066)

**Comment by JulianvDoorn** [comment]
I have no idea how these drafts work, am I meant to merge this or is this simply an addition for #1075 ? Also- the travis-ci build fails which prevents merging, I can't seem to reproduce it on my own machine.

**Comment by dota17** [comment]
I think this PR is better.

From the ci report, it fails in the case `Linux xenial gcc cmake coverage`.
The Travis-CI tells that there are some errors when [building and testing with CMake](https://github.com/open-source-parsers/jsoncpp/wiki/Building#building-and-testing-with-cmake).
I try to reproduce it on my own machine. When i build with CMake, i got these following errors:
```
/src/lib_json/../../include/json/value.h:419:13: error: explicit specialization in non-namespace scope 'class Json::Value'
   template <> bool as<bool>() const { return asBool(); }
             ^
....
```
And i got some same build errors when building with meson/ninja.

**Comment by BillyDonahue** [comment]
Oh, I forgot you can't specialize a template inside a class.
You just have to move the specializations outside the class.
I did that in 826228e

**Pull request merged**
