### PR TITLE
json/config.h: Generalize setting of JSONCPP_OVERRIDE to all compilers

### PR DESCRIPTION
**Pull request by jcfr**
This commit has been adapted from InsightSoftwareConsortium/ITK@1c86090

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @thewtex @aylward

**Comment by thewtex** [comment]
+1

**Comment by jcfr** [comment]
Cc: @cdunn2001

**Comment by cdunn2001** [comment]
I'm fine with this in principle, but if there are complaints from VisualStudio users, we might have to revert this. I seem to recall inconsistent definitions for `_cpluplus` in older VS versions.

**Comment by jcfr** [comment]
Thanks for reviewing and integrating. If there are any issues, I will make sure to follow up.

Otherwise, if you are willing to change the minimum required CMake version from CMake `2.8.5`  to at least CMake `3.2`, we could use the module [WriteCompilerDetectionHeader](https://cmake.org/cmake/help/v3.2/module/WriteCompilerDetectionHeader.html#module:WriteCompilerDetectionHeader).

Let me know if that sound reasonable.

**Comment by cdunn2001** [comment]
That might have to wait for 2.0, unfortunately.

**Comment by jcfr** [comment]
Cc: @vovythevov @fedorov

**Pull request merged**
