### PR TITLE
Add explicit type conversions into type checks functions

### PR DESCRIPTION
**Pull request by amostyaev**
These conversions are required for stable work of debug build on Android

### CODE REVIEW

**Comment by amostyaev** [comment]
There are some problems in Int64 tests. I'm not sure how they should be fixed.

**Comment by cdunn2001** [comment]
Test failure:

```cpp
Testing RValueTest/moveConstruction: OK

* Detail of ValueTest/integers test failure:

../src/test_lib_json/main.cpp(825): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1313): check.isInt_ == value.isInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(828): !val.isConvertibleTo(Json::intValue)

../src/test_lib_json/main.cpp(851): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1313): check.isInt_ == value.isInt()

    Expected: false

    Actual  : true

  ../src/test_lib_json/main.cpp(1314): check.isUInt_ == value.isUInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(854): !val.isConvertibleTo(Json::intValue)

../src/test_lib_json/main.cpp(855): !val.isConvertibleTo(Json::uintValue)

../src/test_lib_json/main.cpp(903): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1313): check.isInt_ == value.isInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(906): !val.isConvertibleTo(Json::intValue)

../src/test_lib_json/main.cpp(927): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1313): check.isInt_ == value.isInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(930): !val.isConvertibleTo(Json::intValue)

../src/test_lib_json/main.cpp(978): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1313): check.isInt_ == value.isInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(981): !val.isConvertibleTo(Json::intValue)

../src/test_lib_json/main.cpp(1027): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1314): check.isUInt_ == value.isUInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(1031): !val.isConvertibleTo(Json::uintValue)

../src/test_lib_json/main.cpp(1073): checkIs(val, checks)

  ../src/test_lib_json/main.cpp(1314): check.isUInt_ == value.isUInt()

    Expected: false

    Actual  : true

../src/test_lib_json/main.cpp(1077): !val.isConvertibleTo(Json::uintValue)

56/57 tests passed (1 failure(s))
```
Possibly, the tests themselves need to be fixed? But that could be a backward incompatible change.

**Comment by cdunn2001** [comment]
Status? Still needed?

**Comment by amostyaev** [comment]
I edited teh sources locally. But I do not know how the test should be fixed..

**Comment by cdunn2001** [comment]
Ok. I might have time to look at those over the holidays. Are these still the exact changes you want? Could you explain exactly why these are needed? (Just compiler errors? If so, what compiler?)

**Comment by amostyaev** [comment]
Without these explicit conversions I got crash on Android when trying to retrieve `1` as int.
It's strange that this happened only at debug build.

Android Studio uses `clang` compiler.I'm not sure about the exact version, as I updated my IDE several times since the issue has been fixed with my commit.

**Comment by cdunn2001** [comment]
We test Clang on Linux. That should be the same. What version of clang do you use? Can you update clang in Andriod Studio?

**Comment by amostyaev** [comment]
I use Clang version 5.0.300080.

**Comment by cdunn2001** [comment]
```sh
$ clang++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
```

**Comment by amostyaev** [comment]
The command results into the following for me:
`Android clang version 5.0.300080  (based on LLVM 5.0.300080)`

**Comment by cdunn2001** [comment]
Is this still an issue for you? Maybe a recent commit addressed this?

**Comment by amostyaev** [comment]
Thanks for the notice. I'll check it today or at Monday.

**Comment by amostyaev** [comment]
Looks like the issue was gone. I'm not sure it was fixed by a commit or sime changes in the Android Studio, but the latest version from `master` doesn't crash as previous.

**Pull request closed without merging**
