### PR TITLE
Fix empty version string in pkgconfig/jsoncpp.pc

### PR DESCRIPTION
**Pull request by dota17**
Hi @AmarOk1412 Please check if this patch fix your problem.

Fix https://github.com/open-source-parsers/jsoncpp/issues/1235

### CODE REVIEW

**Comment by AmarOk1412** [comment]
```
File: pkg-config/jsoncpp.pc
────────────────────────────────────────────────────────
prefix=/usr/local
exec_prefix=/usr/local
libdir=${exec_prefix}/lib64
includedir=${prefix}/include

Name: jsoncpp
Description: A C++ library for interacting with JSON
Version: 1.9.4
URL: https://github.com/open-source-parsers/jsoncpp
Libs: -L${libdir} -ljsoncpp
Cflags: -I${includedir}

```

Looks good :)

**Comment by baylesj** [comment]
I was curious how this happened, it looks like its a result of [this patch](https://github.com/open-source-parsers/jsoncpp/commit/cfc1ad72ad7e0a6d625686182bce1aefa118b308), which removed cmake `JSONCPP_` prepended fields in favor of `PROJECT_` field, in this case `JSONCPP_VERSION` got changed to`PROJECT_SOVERSION`.

**Comment by baylesj** [comment]
@cdunn2001 or @BillyDonahue, do you think any projects are going to be checking the `JSONCPP_VERSION*` fields? If so, I'm wondering if the right answer is to actually batch replace `PROJECT_VERSION*` with `JSONCPP_VERSION*` (essentially partially reverting https://github.com/open-source-parsers/jsoncpp/pull/1197).

**Comment by dota17** [comment]
@baylesj Sorry, my bad, you are right. I shouldn't change the project setting in CMakelists.txt.
I didn't know that `<PROJECT-NAME>_VERSION` and `PROJECT_VERSION` are the same[[1](https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_VERSION.html#variable:%3CPROJECT-NAME%3E_VERSION),[2](https://cmake.org/cmake/help/latest/variable/PROJECT_VERSION.html#variable:PROJECT_VERSION)], so there is no need to change the project name from `JSONCPP` to `jsoncpp`.
So, based on this, I agree with you to partially reverting #1197, use `JSONCPP_VERSION` and `JSONCPP_VERSION_MAJOR` again.

**Comment by cdunn2001** [comment]
I honestly have no opinion on any cmake changes. I'd aim for minimal maintenance, but I wouldn't object to any cmake changes.

**Comment by AmarOk1412** [comment]
Note here: with the PR I still have an undetected JSONCPP version
It's for building https://github.com/savoirfairelinux/opendht

**Comment by dota17** [comment]
@AmarOk1412  
Could you please tell more detail?

**Comment by LocutusOfBorg** [comment]
For Debian, I went for a minimal approach:
```
--- libjsoncpp-1.9.4.orig/CMakeLists.txt
+++ libjsoncpp-1.9.4/CMakeLists.txt
@@ -73,6 +73,7 @@ project(jsoncpp
         LANGUAGES CXX)

 message(STATUS "JsonCpp Version: ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")
+set(JSONCPP_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})
 set(PROJECT_SOVERSION 24)

 option(JSONCPP_WITH_TESTS "Compile and (for jsoncpp_check) run JsonCpp test executables" ON)
```

**Comment by cdunn2001** [comment]
I guess #1235 fixed this? Please re-open if not.

**Pull request closed without merging**
