### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by datadiode**
Side note: The integration branch is just for my convenience. I don't mean to propose creation of a new branch in the mainline repo.

### CODE REVIEW

**Comment by cdunn2001** [comment]
> Side note: The integration branch is just for my convenience. I don't mean to propose creation of a new branch in the mainline repo.

Of course! You're using github properly. Thanks! I'll look at this soon...

**Comment by cdunn2001** [comment]
Please rebase to `master`. You'll just have to fix a couple small conflicts.

**Comment by datadiode** [comment]
`readToken()` has already consumed the first character - be it a sign or a digit - by the time `readNumber()` gains control. A leading `+` is illegal and triggers `readToken()`'s `default:` case.

The goal is to not read beyond a valid token. `sscanf()` tolerates extra characters at the end of its input, so the malformedness remains undetected when `readNumber()` silently skips them.

Existing tests run without issues. It would make some sense to add a test that checks parser behavior with malformed input.

About rebase: I'm currently on subversion which does not seem to offer me that option.
Seems like a good time to start with git.

**Comment by cdunn2001** [comment]
> `readToken()` has already consumed the first character

Oh! Of course! I should have looked at that.

**Comment by cdunn2001** [comment]
I've integrated your fix for `fail31.json`. Let's make a new issue for other changes.

**Pull request closed without merging**
