### PR TITLE
Add pragma pack directive

### PR DESCRIPTION
**Pull request by sergiy80**
Added pragma pack directive to jsoncpp headers.
Related to https://github.com/open-source-parsers/jsoncpp/issues/458

### CODE REVIEW

**Comment by sergiy80** [comment]
To reproduce the issue.
In Visual Studio project (makefiles/msvc2010) just change **test_lib_json**'s **_Struct Memeber Alignment_** option from Default (8) to 2, leaving **lib_json**'s option as is (Default).
Without this commit **test_lib_json.exe** will produce either failed tests or abnormal termination.

**Comment by cdunn2001** [comment]
Was this a problem anywhere other than Windows/VisualStudio?

**Comment by sergiy80** [comment]
Also I could reproduce seg fault error compiling jsoncpp using gcc and clang under MSYS2 environment.
Beause linux standard system headers do not have packing guards (unlike VS standard headers), it is not possible just to use packing option other then default (8) for whole project.
To reproduce the crash need to modify _jsontest.cpp_ and _main.cpp_ in **_test_lib_json_** project to exclude standard headers from changing packing opton.
The diffs are below.
With these changes in the test project the results are the same as for VS project, failed tests and segmentation fault error.

```diff
diff --git a/src/test_lib_json/jsontest.cpp b/src/test_lib_json/jsontest.cpp
index 4c10a37..08e193f 100644
--- a/src/test_lib_json/jsontest.cpp
+++ b/src/test_lib_json/jsontest.cpp
@@ -68,6 +68,8 @@
 #include <windows.h>
 #endif // if defined(_WIN32)
 
+#pragma pack(2)
+
 namespace JsonTest {
 
 // class TestResult
```

```diff
diff --git a/src/test_lib_json/main.cpp b/src/test_lib_json/main.cpp
index 47cd981..623a692 100644
--- a/src/test_lib_json/main.cpp
+++ b/src/test_lib_json/main.cpp
@@ -3,15 +3,19 @@
 // recognized in your jurisdiction.
 // See file LICENSE for detail or copy at http://jsoncpp.sourceforge.net/LICENSE
 
-#include "jsontest.h"
-#include <json/config.h>
-#include <json/json.h>
+
 #include <cstring>
 #include <limits>
 #include <sstream>
 #include <string>
 #include <iomanip>
 
+#pragma pack(2)
+#include "jsontest.h"
+#include <json/config.h>
+#include <json/json.h>
+
 // Make numeric limits more convenient to talk about.
 // Assumes int type in 32 bits.
 #define kint32max Json::Value::maxInt
```

**Comment by cdunn2001** [comment]
Thanks. Very interesting. I did not know about this pragma.

**Pull request merged**
