### PR TITLE
Allow trailing comma in objects and arrays

### LINKED ISSUE #1043: Ignore trailing comma in objects and arrays
**Is your feature request related to a problem? Please describe.**
I use the [new Windows Terminal](https://github.com/microsoft/terminal), which uses JsonCpp for parsing JSON configuration files, and currently requires those configuration files to be manually edited. It provides [a file with defaults](https://github.com/microsoft/terminal/blob/06bd7e22da183619b99b632e10e186d441b05e45/src/cascadia/TerminalApp/defaults.json), from which I copy paste lines with settings for individual profiles (represented as JSON objects) into my user configuration file, then change the default values. However, those setting lines end with a comma, so if I paste them at the end of an existing profile object and forget to remove the comma, JsonCpp will fail to parse the configuration file and the Windows Terminal will pop up with a "Failed to reload settings" dialog.

More generally, this problem occurs for both objects and arrays when manually constructing JSON files or copy-pasting objects from ECMAScript code, which ignores trailing commas in object and array literals.

**Describe the solution you'd like**
I want JsonCpp, either by default or with a configuration setting, to ignore one trailing comma in objects and arrays while deserializing. I don't expect JsonCpp to keep any reference of this trailing comma or to be able to recreate it while serializing.

**Describe alternatives you've considered**
The main alternative I see is to keep the current behavior and to strictly enforce the correctness of parsed JSON. However, JsonCpp already supports comments, which is non-standard, so supporting trailing commas doesn't seem at odds with the direction of the project.

Between the alternatives of ignoring a trailing comma by default or by configuration, this depends on whether JsonCpp is allowed to break backwards compatibility by parsing files that would previously have resulted in an syntax error. I don't know the project stance on this.

JsonCpp could optionally support retaining and serializing trailing commas, but I don't see any value in that, except being able to more faithfully reproduce the source when deserializing and reserializing a file.

**Additional context**
This feature was also requested back in 2006 [on Sourceforge](https://sourceforge.net/p/jsoncpp/feature-requests/4/). @cdunn2001 back then remarked:

> I see this is difficult the way readObject() and readArray() are written. Oh, well. It would be nice someday...

### PR DESCRIPTION
**Pull request by kimsey0**
Fixes #1043.

Allows one trailing comma in objects (`{ "count" : 1234, } = { "count" : 1234 }`) and arrays (`[1,] = [1]`), which is ignored.

Introduces new feature `allowTrailingCommas`, which can be used to switch this on and off. It is enabled by default, unless in strict mode.

Currently only allows trailing commas in arrays if `allowDroppedNullPlaceholders` is off, since otherwise, we'd break clients that depend on `[1,]` being parsed as `[1,null]`.

In this draft version, introduces the changes both in the legacy `Reader` and the modern `OurReader`. However, this can be changed if https://github.com/open-source-parsers/jsoncpp/pull/1053#discussion_r335987776 is handled and we allow having _modern only_ tests.

### CODE REVIEW

**Comment by cdunn2001** [comment]
I like this feature. I personally use trailing commas in Python all the time. But (A) this PR currently fails for AppVeyor. And (B) it's still a draft. Is that because of the problem with old versus new Reader in the tests?

**Comment by kimsey0** [comment]
(A) just seems to be because I haven't run clang-format. I'll get that done.

(B) is because of the problem with old versus new Reader. I have currently implemented the change in both the old and new Reader, but from https://github.com/open-source-parsers/jsoncpp/issues/1043#issuecomment-542957244, it sounds like I should revert the change to the old reader, since it's deprecated and shouldn't be changed. In that case, in order for the tests I have added to pass, we will need the change in https://github.com/open-source-parsers/jsoncpp/pull/1053/commits/836d954176f88325b82662903e4e365a4ebac03a to be merged, so that the tests are only run for the new Reader.

**Comment by kimsey0** [comment]
@cdunn2001: Would you prefer to have support for trailing slashes in both the old and the new Reader, or just in the new one?

**Comment by cdunn2001** [comment]
Trailing "slashes"? If you mean trailing "commas", just in New is fine. But we need to be sure we have test coverage first.

**Comment by kimsey0** [comment]
Yes, I mean trailing commas. I've edited it in the comment above.

Let's keep this pull request as a draft until https://github.com/open-source-parsers/jsoncpp/pull/1053 is merged. Then I'll revert the changes to the old Reader.

**Comment by cdunn2001** [comment]
We can merge #1053 after clang-format there. Then yes, we can merge this one.

**Comment by dota17** [comment]
Ready for review! I think we can go to the next step now.

**Comment by cdunn2001** [comment]
replaced by #1098

**Pull request closed without merging**
