### PR TITLE
ENH: Prevent cmake in source builds

### PR DESCRIPTION
**Pull request by hjmjohnson**
Building directly inside the root of the source tree
can cause problems where the build intermediate files
overwrite or conflict with the intended source code
files.

This modification identifies this problem and
issues failure messages and suggestions to over
come the problem with more robust build suggestion.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
See #1087 for motivation for this improvement.

**Comment by baylesj** [comment]
It looks like this change requires built bot reconfiguration.  If you can change the AppVeyor config to not build in the source directory, I'm happy to approve this patch.

**Comment by dota17** [comment]
@hjmjohnson I think this issue can move forward now. Would you like to take a little time to look at this PR to move it forward?

**Comment by cdunn2001** [comment]
@hjmjohnson, we've merged the clang-tidy fixes. Maybe that will help you fix VisualStudio? Otherwise, let's close this.

**Comment by baylesj** [comment]
@cdunn2001, I think? I've fixed the appveyor issue, it's a valid one. I know our CMake support is deprecated but I'm still interested in landing this patch.

**Comment by baylesj** [comment]
I think this is a good step forward.

**Comment by baylesj** [comment]
Travis is being slow, but it's all green so going to submit.

**Comment by gizmocuz** [comment]
Sorry for asking, but we use your library as a sub project and build this via:

  add_subdirectory (extern/jsoncpp EXCLUDE_FROM_ALL)
  target_link_libraries(domoticz jsoncpp_static)

With this change it's not possible to build this anymore

Could you make this an Option which is default set to YES, but when used as a external library in other projects we can set this to NO ?

**Comment by brucemiranda** [comment]
This has caused me a problem Building jsoncpp today. In the end I had to comment the two new lines added in the CMakelists within the json folder.

**Comment by gizmocuz** [comment]
I forked this repo, and now use my copy with also these two lines removed
This is not standard CMake, and it should not cause problems when building in the main folder and overwrite intermediate and source code files.
If it does, something else is wrong.
Sure it is best practice to create a build folder, but I would not force this...

@baylesj , @hjmjohnson , hope you can reconsider this patch

**Comment by cdunn2001** [comment]
@baylesj , it was a good try, but I guess we need to revert at least some part of this. What do you think? The objections from these users seem valid.

**Pull request merged**
