### PR TITLE
Avoid redundant depreciation warnings in Visual Studio 2012

### PR DESCRIPTION
**Pull request by lanzkron**
See the following [stackoverflow question](https://stackoverflow.com/questions/46151531/how-works-deprecated-warnings-and-how-to-remove-them-when-using-jsoncpp), deprecation warnings will show up even if nothing is used.

**Note:** I'm not able to clone the repository to my computer at the moment so this pull request was created on the web, please make sure it's OK.

### CODE REVIEW

**Comment by cdunn2001** [comment]
Moved to #669.

**Comment by jpo38** [comment]
@cdunn2001 Note that VS still reports deprectaed warning for `StyledStreamWriter` attributes childValues_, indentString_, indentation_ when json.h is included...it's unclear why it does that.

> d:\dev\vobs_ext_2015\libcpp\jsoncpp\jsoncpp-1.8.3\include\json\writer.h(283): warning C4996: 'Json::StyledStreamWriter::childValues_': Use StreamWriterBuilder instead
> d:\dev\vobs_ext_2015\libcpp\jsoncpp\jsoncpp-1.8.3\include\json\writer.h(310): note: see declaration of 'Json::StyledStreamWriter::childValues_'
> d:\dev\vobs_ext_2015\libcpp\jsoncpp\jsoncpp-1.8.3\include\json\writer.h(283): warning C4996: 'Json::StyledStreamWriter::indentString_': Use StreamWriterBuilder instead
> d:\dev\vobs_ext_2015\libcpp\jsoncpp\jsoncpp-1.8.3\include\json\writer.h(312): note: see declaration of 'Json::StyledStreamWriter::indentString_'
> d:\dev\vobs_ext_2015\libcpp\jsoncpp\jsoncpp-1.8.3\include\json\writer.h(283): warning C4996: 'Json::StyledStreamWriter::indentation_': Use StreamWriterBuilder instead
> d:\dev\vobs_ext_2015\libcpp\jsoncpp\jsoncpp-1.8.3\include\json\writer.h(314): note: see declaration of 'Json::StyledStreamWriter::indentation_'

**Comment by cdunn2001** [comment]
@jpo38, So we do need to push/pop the same thing for StyledStreamWrite? Or do we need to push a different suppression number? (I have no easy way to test this.)

**Comment by jpo38** [comment]
Yes, apparently this fixes it. And you'll later get the deprecated warning if you instantiate the class, what's expected.

**Comment by cdunn2001** [comment]
I unpushed. StyledStreamWriter should now suppress the warnings. Let me know if there is a problem.

**Comment by jpo38** [comment]
Works fine now.

By the way, did you get a chance to test this with g++. Because maybe it will complain that pragma is not recognized. You may need to protect the added lines by a `#ifdef _MSC_VER` check.

Thank you for the quick fix.

**Comment by cdunn2001** [comment]
We test both gcc and clang on Linux in TravisCI, and Microsoft on AppVeyor.

**Pull request closed without merging**
