### PR TITLE
Fix for #798

### PR DESCRIPTION
**Pull request by cinemast**
Add preprocessor definitions for MSVC dllexport/dllimport statements

### CODE REVIEW

**Comment by cinemast** [comment]
I don't know why the gcc build is failing. It does not seem to be related to the changes.

**Comment by cdunn2001** [comment]
TravisCI might have deleted gcc-4.9. I'm asking them for advice on how to proceed.

**Comment by cdunn2001** [comment]
This passed 6 days ago: https://travis-ci.org/open-source-parsers/jsoncpp/builds/393044263?utm_source=github_status&utm_medium=notification

Maybe TravisCI changed very recently.

**Comment by cdunn2001** [comment]
Hmmm. This is strange. Your base commit rebuilds fine:
* https://travis-ci.org/cdunn2001/jsoncpp/builds/387473945

I've rebased your change onto our `master`, and it still fails:
* https://travis-ci.org/open-source-parsers/jsoncpp/jobs/395927931

I think the problem may be the `''` here (after fPIC):
```
g++-4.9 -Ijsoncpp@sha -I. -I.. -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall\
 -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -fPIC ''  -MD \
 -MQ 'jsoncpp@sha/src_lib_json_json_value.cpp.o' \
 -MF 'jsoncpp@sha/src_lib_json_json_value.cpp.o.d' \
 -o 'jsoncpp@sha/src_lib_json_json_value.cpp.o' -c ../src/lib_json/json_value.cpp
```
I think your new string is being substituted wrong...

**Comment by cdunn2001** [comment]
Yes, a successful run has this:
```
[1/9] g++-4.9 -Ijsoncpp_test@exe -I. -I.. -I../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O3  -MD -MQ 'jsoncpp_test@exe/src_test_lib_json_jsontest.cpp.o' -MF 'jsoncpp_test@exe/src_test_lib_json_jsontest.cpp.o.d' -o 'jsoncpp_test@exe/src_test_lib_json_jsontest.cpp.o' -c ../src/test_lib_json/jsontest.cpp
```

For some reason, **clang** doesn't mind the empty-string argument, but **g++** has a problem with it.

**Comment by cdunn2001** [comment]
**Meson** needs `[]` instead of `''` for empty-string. Fixing in #800.

**Pull request closed without merging**
