### PR TITLE
make the unix cmake example work

### PR DESCRIPTION
**Pull request by bmyerz**
...by setting the archive directory variable

### CODE REVIEW

**Comment by cdunn2001** [comment]
Could you explain this change? I use the example as-is all the time. What exactly was broken, and how does this change it?

**Comment by bmyerz** [comment]
I did the following from a fresh copy.
```bash
cd src
mkdir -p build/debug
cd build/debug
cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -G "Unix Makefiles" ../..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /sampa/share/gcc-4.8.2/rtf/bin/gcc
-- Check for working C compiler: /sampa/share/gcc-4.8.2/rtf/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /sampa/share/gcc-4.8.2/rtf/bin/g++
-- Check for working CXX compiler: /sampa/share/gcc-4.8.2/rtf/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at lib_json/CMakeLists.txt:66 (INSTALL):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "jsoncpp_lib_static".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

Apparently the location to put the .a file must be specified. I'm not sure if there is a default value for variable `ARCHIVE_INSTALL_DIR` in src/lib_json/CMakeLists.txt

**Comment by cdunn2001** [comment]
What version of **cmake** did you use? And which branch/commit of **jsoncpp**?

Seems like a good change. I just want to be clear about the problem, since I have not seen this.

**Comment by bmyerz** [comment]
Here is the relevant info I could think of.

```bash
$ cmake --version
cmake version 2.8.12

$ uname -a
Linux hostname 2.6.32-504.12.2.el6.x86_64 #1 SMP Sun Feb 1 12:14:02 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu

$ git log -n 1
commit 64441486ace99abee0371a3481632fe0d1400cca
Merge: d5e54d2 31e9962
Author: Christopher Dunn <cdunn2001@gmail.com>
Date:   Tue May 19 01:53:11 2015 -0500

    Merge pull request #275 from stefan-it/stefan/cmake-generator-fix

    [Documentation][Markdown] Use correct help option for cmake.

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/sampa/share/gcc-4.8.2/rtf/libexec/gcc/x86_64-unknown-linux-gnu/4.8.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /sampa/share/gcc-4.8.2/src/gcc-4.8.2/configure --disable-cloog-version-check --disable-ppl-version-check --enable-cloog-backend=isl --enable-gold --enable-languages=c,c++ --enable-lto --enable-libssp --prefix=/sampa/share/gcc-4.8.2/rtf --with-cloog=/sampa/share/gcc-4.8.2/rtf --with-gmp=/sampa/share/gcc-4.8.2/rtf --with-mlgmp=/sampa/share/gcc-4.8.2/rtf --with-mpc=/sampa/share/gcc-4.8.2/rtf --with-mpfr=/sampa/share/gcc-4.8.2/rtf --with-ppl=/sampa/share/gcc-4.8.2/rtf
Thread model: posix
gcc version 4.8.2 (GCC)

$ python --version
Python 2.7.6
```

**Comment by cdunn2001** [comment]
Hmmm. I am using cmake-3.2.2. I guess it's not required anymore.

**Pull request merged**
