### PR TITLE
CMake: Unique lib target name 

### PR DESCRIPTION
**Pull request by jschueller**
An issue when using the imported target from the cmake config file is that the target name differs whether the lib is compiled statically of dynamically so the client code cannot know easily whether to use the dynamic name (jsoncpp_lib) or the static name (jsoncpp_lib_static).

This PR sets a unique name for the lib so the client code can always use:
```
find_package (jsoncpp NO_MODULE REQUIRED)
target_link_libraries (client_target jsoncpp_lib)
```

Also BUILD_STATIC_LIBS is unused and not standard.

And also use CMAKE_CROSSCOMPILING_EMULATOR to run tests when cross-compiling.

### CODE REVIEW

**Comment by jschueller** [comment]
ping @open-source-parsers/jsoncpp

**Comment by jschueller** [comment]
ping @cdunn2001

**Comment by cdunn2001** [comment]
We strongly prefer **meson** to **cmake**, but if you are confident in this change, go ahead and merge. You might help other **cmake** users.

**Comment by jschueller** [comment]
@cdunn2001 I dont have rights to merge

**Pull request merged**
