### PR TITLE
Fix missing initialization in Constructor.

### PR DESCRIPTION
**Pull request by ya1gaurav**
OurFeatures() Constructor is not initializing variable rejectDupKeys_.

### CODE REVIEW

**Comment by pavel-pimenov** [comment]
cppcheck 1.69 
Member variable 'OurFeatures::stackLimit_' is not initialized in the constructor.
Member variable 'OurReader::stackDepth_' is not initialized in the constructor.

**Comment by BillyDonahue** [comment]
pavel has a point. Maybe go a little further and initialize the other fields while we're here.

**Comment by ya1gaurav** [comment]
stackLinit_ initialized in https://github.com/open-source-parsers/jsoncpp/pull/364
It wil make OurFeatures to be free from above cppcheck , other pull request can be done for OurReader.

**Comment by cdunn2001** [comment]
Instead, let's delete the whole ctor. We can accept C++ defaults b/c they are always over-ridden in `newCharBuilder()`.

But yes, let's update the OurReader ctor. I don't want to refactor that class since it is mainly a copy of old code.

**Pull request closed without merging**
