### PR TITLE
Compiles jsoncpp with QNX 6.6

### PR DESCRIPTION
**Pull request by antonindrawan**

### CODE REVIEW

**Comment by cdunn2001** [comment]
Seems good. Please rebase after #371 and re-test. Then we'll merge.

**Comment by antonindrawan** [comment]
Hi Christoper,

It still compiles after merging PR 371.

It was my first time with re-basing and I got some error messages when doing a git push:
" hint: Updates were rejected because the tip of your current branch is behind".

Anyway, it seems that PR 371 is already merged to my branch and it still compiles 

Regards,
Anton

**Comment by cdunn2001** [comment]
`git push -f origin QNX_support`

You need `-f` because it's a "rebase", not a "fast-forward". Try again. It's worth learning, and it saves me some time. We don't want that new merge commit. You shouldn't need that if you rebase onto the tip of master. Try `rebase -i` to get rid of it.

Anyway, try it once more. I'll rebase myself if you still have trouble.

**Comment by antonindrawan** [comment]
Thanks for your hint about the -f option.

I just reverted the merge commit and pushed it to QNX_support. Hopefully, it is now fine to merge it.
Please let me know.

Meanwhile, I keep practising git rebase and push on my playground repo :)

**Pull request merged**
