### PR TITLE
Issue #958: Travis CI should enforce clang-format standards

### PR DESCRIPTION
**Pull request by baylesj**
This patch adds clang format support to the travis bots.

### CODE REVIEW

**Comment by baylesj** [comment]
Any issues with pulling the run-clang-format.py script? It's MIT licensed.

**Comment by dota17** [comment]
Some questions for me.

1. After running these command from [Building](https://github.com/open-source-parsers/jsoncpp/wiki/Building)
> cd jsoncpp/
BUILD_TYPE=release
#plain, debug, debugoptimized, release, minsize
LIB_TYPE=shared
#LIB_TYPE=static
meson --buildtype ${BUILD_TYPE} --default-library ${LIB_TYPE} . build-${LIB_TYPE}
ninja -v -C build-${LIB_TYPE} test

I run 
```
ninja -v -C build-${LIB_TYPE} clang-format
```
and I got these changes (some changes were wrong)  : 
[run-clang-format.txt](https://github.com/open-source-parsers/jsoncpp/files/3619165/run-clang-format.txt)

2. From PR #1025 , I found that
`Value& root` and `IStream & is, Value & root`
before char `&`,  some places have a blank, some places have no.

3. To test this PR, I run some tests by pushing some wrong format codes. It is OK to check the wrong format.
But the third test [`Mac clang meson static release testing`] is error, and the error message is
`run-clang-format.py: error: Command 'clang-format --version' failed to start: [Errno 2] No such file or directory`
Is it better to remove format check in third test or update the env?

**Comment by baylesj** [comment]
1.  This should not change the results of ninja clang-format at all, so I'm not sure what the cause of what you are seeing is. This only affects Travis.

2. Yeah, I'm thinking that our clang format configuration could use some changes, it's not exactly what I would like it to be.

3. I can fix that, I think clang format isn't installing properly on the mac bot then.

**Comment by dota17** [comment]
hi, I have checked the new commit and find the question 2 and 3 have been repaired. 
however, as for the question 1,I have some questions.
1. After merging the fix-deprecated to clang-formatize and building, I get this result: 
[test.txt](https://github.com/open-source-parsers/jsoncpp/files/3626195/test.txt)
```
+[[noreturn]] void throwRuntimeError(String const& msg) {
+  abort();
+}[[noreturn]] void throwLogicError(String const& msg) {
+  abort();
+}
```
this change is wrong and it means this clang-format standards  still have some questons.

2. the clang-format result in local is different from the result of Travis CI. 
I run `./travis_scripts/run-clang-format.sh`  in my local computer and get the same changes with test.txt. 
```
run-clang-format.sh: 3: run-clang-format.sh: Bad substitution
--- /root/jsoncpp/community/jsoncpp/.travis_scripts/../src/lib_json/json_value.cpp      (original)
+++ /root/jsoncpp/community/jsoncpp/.travis_scripts/../src/lib_json/json_value.cpp      (reformatted)
@@ -206,14 +206,17 @@
 Exception::~Exception() JSONCPP_NOEXCEPT {}
 char const* Exception::what() const JSONCPP_NOEXCEPT { return msg_.c_str(); }
 RuntimeError::RuntimeError(String const& msg) : Exception(msg) {}
-LogicError::LogicError(String const& msg) : Exception(msg) {}
-[[noreturn]] void throwRuntimeError(String const& msg) {
+LogicError::LogicError(String const& msg)
+    : Exception(msg){}[[noreturn]] void throwRuntimeError(String const& msg) {
   throw RuntimeError(msg);
 }
 [[noreturn]] void throwLogicError(String const& msg) { throw LogicError(msg); }
 #else // !JSON_USE_EXCEPTION
-[[noreturn]] void throwRuntimeError(String const& msg) { abort(); }
-[[noreturn]] void throwLogicError(String const& msg) { abort(); }
+[[noreturn]] void throwRuntimeError(String const& msg) {
+  abort();
+}[[noreturn]] void throwLogicError(String const& msg) {
+  abort();
+}
 #endif

 // //////////////////////////////////////////////////////////////////
@@ -227,7 +230,9 @@
 // Notes: policy_ indicates if the string was allocated when
 // a string is stored.

-Value::CZString::CZString(ArrayIndex index) : cstr_(nullptr), index_(index) {}
+Value::CZString::CZString(ArrayIndex index)
+    : cstr_(nullptr), index_(index) {
+}

 Value::CZString::CZString(char const* str, unsigned length,
                           DuplicationPolicy allocate)

```

The results are same.

**Comment by dota17** [comment]
The Travis CI checks were not successful, Fixed it by #1036

**Comment by dota17** [comment]
The above problem in my local env had been solved.
Tips: use the current version - `clang-8` and `clang-format-8`

**Comment by cdunn2001** [comment]
Very nice!

**Comment by cdunn2001** [comment]
Hmmm. Today I hit a tiny clang-format error. I guess we have to run clang-format now locally before pushing. I've added a script for that in #1229. I hope different versions of clang-format don't disagree with each other.

**Pull request merged**
