### PR TITLE
Fix shared/static lib build conflict

### LINKED ISSUE #631: fails to build with shared libs enabled on msvc
see:
https://github.com/open-source-parsers/jsoncpp/pull/630

### PR DESCRIPTION
**Pull request by jschueller**
When both static and shared lib build are enabled, there is a conflict between the static and import lib ; both are named jsoncpp.lib and the test was incorrectly linked to the static lib but built with JSON_DLL flag and so failed to import symbols with the dllimport keyword. We propose to fix this by appending a "_static" suffix to the static lib when the shared lib is also enabled, so as by default (shared=0, static=1) the behavior is still the same.
This fixes #631.

Also, the appveyor script was messy and mixed msvc versions and 32/64 bits configurations.

### CODE REVIEW

**Comment by cdunn2001** [comment]
appveyor build failed.

**Comment by jschueller** [comment]
yes, see #631

**Comment by jschueller** [comment]
@cdunn2001 there is a conflict between the static and import lib both named jsoncpp.lib, 24114ff fixes this by appending a _static suffix to the static lib if the shared lib is also enabled.

**Comment by cdunn2001** [comment]
Thanks for the appveyor changes!

**Pull request merged**
