### PR TITLE
Use std::aligned_storage for static JSON null

### PR DESCRIPTION
**Pull request by ya1gaurav**
Patch for https://github.com/open-source-parsers/jsoncpp/issues/184
All test cases pass for x86 and Arm compiler.

### CODE REVIEW

**Comment by ya1gaurav** [comment]
Does travis compiler support C++-11 ?

**Comment by ya1gaurav** [comment]
As seen in travis:
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
It does not support C++11.

**Comment by cdunn2001** [comment]
I'd like someone else to look at this. And note that we have to merge this into the `0.y.z` branch somehow too, where C++11 is only a special case.

**Comment by ya1gaurav** [comment]
But std::aligned_storage is since C++-11, so i think it can be merged to 1.y.z branch only.

**Comment by datadiode** [comment]
I dare propose the following:
```
static const union {
  char placeholder[sizeof(Value)];
  double alignment;
} kNull = {""};
```

**Comment by hjmjohnson** [comment]
This issue has become stale due to inactivity.  If you want this issue to be reviewed again, please update the PR resolving the merge conflicts and re-open this issue.

Closing until updated information is provided.

**Pull request closed without merging**
