### PR TITLE
Delete JSONCPP_DEPRECATED, use [[deprecated]] instead.

### PR DESCRIPTION
**Pull request by dota17**
**Language Conformance**: Deletion of JSONCPP_DEPRECATED in favor of C++11's language standard [[deprecated]]

### CODE REVIEW

**Comment by dota17** [comment]
The build failed in Visual Studio 2015. and the compiler showed that:
`C:\projects\jsoncpp\src\lib_json\..\..\include\json/reader.h(55): error C2416: attribute 'deprecated("Use CharReader and CharReaderBuilder instead")' cannot be applied in this context.`
it seems that there is a bug in Visual Studio 2015:
[Wrong compilation error for deprecated nested friend function](https://developercommunity.visualstudio.com/content/problem/138957/wrong-compilation-error-for-deprecated-nested-frie.html)
[Did Visual Studio 2015 Update 3 Break Constructor Attributes?](https://stackoverflow.com/questions/38378693/did-visual-studio-2015-update-3-break-constructor-attributes)

**Comment by baylesj** [comment]
Added a new issue for this, #981

**Comment by baylesj** [comment]
Good catch, I should have noticed this. If you fix the merge conflicts, this should be good to go!

**Comment by dota17** [comment]
> Good catch, I should have noticed this. If you fix the merge conflicts, this should be good to go!

Hi baylesj, the merge conflict  have been fixed before, it seems that this branch has no merge conflict now.

**Comment by baylesj** [comment]
I still see the "This branch cannot be rebased due to conflicts"

**Comment by dota17** [comment]
> I still see the "This branch cannot be rebased due to conflicts"

I uploaded an update, and the conflit check passed. Thanks to you can see more details than me, so if there are any problem, please tell me.

**Comment by dota17** [comment]
Actually, `[[deprecated]]` is a feature in C++14, I made a typo in description:

> Language Conformance: Deletion of JSONCPP_DEPRECATED in favor of ~~C++11~~C++14's language standard [[deprecated]]

Tips：this  #978 PR is wrote for #975 [Migrate to C++14].

Maybe there will be some compatibility problems like issue #990.

**Pull request merged**
