### PR TITLE
DRAFT: Format python for python36

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by cdunn2001** [comment]
This is mostly changing single-quote to double-quote. Harmless, but also pointless.

This also *removes* python2 support, which I assume is the reason for the AppVeyor failure.

Instead of changing this, we might be better off with a better test-framework and test-runners. We need to be able to run slightly different tests with different JSON Readers/Writers and configuration. (See other Issue.)

**Comment by hjmjohnson** [comment]
@cdunn2001  I thought that the intent was to remove python 2 support since it is at end of life.  PR #1084 mandates the use of python3 as discussed in #1081.  If we want to continue supporting python 2.7, more work will need to be done to PR#1084.

**Comment by hjmjohnson** [comment]
> This is mostly changing single-quote to double-quote. Harmless, but also pointless.

The point is to provide consistency by following a set of common formatting guides.  Black is one of may tools that can do this automatically.  My experience in other projects is that "giving control to an automated tool" for formatting greatly increased overall productivity, at the expense of a few "pointless" formatting compromises.  That's my 2cents worth of opinion.    This was 2 minutes of work, so I'm perfectly happy with a rejection of this PR.

**Comment by cdunn2001** [comment]
I don't have a problem with dropping python2 support. But AppVeyor does need to pass.

As for running "black", I'm fine with it, but I think maybe we should hold off until we finish some serious refactoring or copy/pasting to ensure that we run separate tests for the old and new Readers. Git-history can be helpful for tracking the provenance of bugs, and a change this large muddies the history.

But after we're stable, I'd be in favor of this PR. (And I'm not *strongly* opposed today.)

**Comment by hjmjohnson** [comment]
@cdunn2001 Thanks.  Let's revisit this after some stability isssues are resolved.  It really is 2-3 minutes of work to remake this PR.

**Comment by baylesj** [comment]
I'm going to close this out as stale. Feel free to revisit this and reopen as appropriate.

**Pull request closed without merging**
