### PR TITLE
Improve CMake correctness and handling

### PR DESCRIPTION
**Pull request by mrjoel**
Update the CMake processing to improve interoperability with being included as CMake from a larger project using jsoncpp.

### CODE REVIEW

**Comment by dota17** [comment]
LGTM.

**Comment by dota17** [comment]
@hjmjohnson Hi Hans, Would you like to take a look at this?

**Comment by cdunn2001** [comment]
@mrjoel, I like this a lot. Thank you! We rely on users to keep the **cmake** files up-to-date.

I am tempted to merge this immediately, but I would like to retain all your commits, for future reference. That means we need to rebase *and* create a merge-commit, the one area where BitBucket is better than GitHub. Would you please rebase your branch, and then create a merge-commit? You will need to use drop-down, since if you simply click "rebase and merge" you would be putting all these commits directly on the `master` branch. If that doesn't make sense, please ask.

**Comment by mrjoel** [comment]
Sure rebasing is fine, but I'm not entirely clear what you're asking for in regards to the merge commit using drop-down (I mainly use git from commandline). You want a single commit for merging which reflects a merge of this branch to master?

**Comment by mrjoel** [comment]
@cdunn2001 Hmm, inadvertently closed when pushing the rebase branch, and I don't seem to have permissions to reopen. Will a maintainer with perms reopen, or should I create a new PR?

**Comment by dota17** [comment]
The branch `mrjoel:mrjoel/cmake-updates` is deleted, so it can not be reopen.
You can create a new PR.

**Comment by mrjoel** [comment]
The branch still exists, just not referenced anymore... perhaps I did a delete with new push instead of force push to update the branch...

**Comment by cdunn2001** [comment]
Oh, I think I could have re-opened it if you'd simply recreated the branch, but now I can't because you already created a new PR for the same branch. Not sure, but I guess that's how GitHub works. Not a big deal though.

**Pull request closed without merging**
